name: govision
description: GoVision is a mobile application that helps you to monitor diabetic retinopathy eye diseases using integrated AI.
version: 1.1.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: 2.3.5
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  easy_localization: ^3.0.7
  flutter_image_compress: ^2.3.0
  camera: ^0.10.1
  json_annotation: ^4.8.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  table_calendar: ^3.1.1
  image_picker: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.7
  build_verify: any
  flutter_gen_runner: any
  freezed: ^2.4.5
  go_router_builder: 2.7.0
  import_sorter: ^4.6.0
  json_serializable: any
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^2.3.8
  rename: ^3.0.2
  very_good_analysis: 4.0.0+1
  flutter_launcher_icons: ^0.13.1

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
  assets:
    - assets/lang/en.json
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    - assets/logo/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_logo_xs.png"
  min_sdk_version: 21